### ISSUE TITLE
Couple of enhancement ideas

### ISSUE THREAD

**Issue by tarchive** [M-rcus/yiff-dl#11]
First off i want to say great work. The program works as it is right now, but i just have ideas for enhancements that will make it even better. (ordered most desired to least)

1. Clean up failed downloads- In my case, I notice that when it downloads a shared zip file and if fails for whatever network reason, it will leave the partial file behind. I must manually test integrity of the archives and redownload incomplete ones to ensure i actually have all the files which is annoying.

2. Add user input flags for download timeout and retry values - As you know the network is not always fast or responsive. Having the option to specify how long to try or how many times to retry would be very helpfully working around the constant 504's and 502's 

3. Specify multiple IDs  - Either specifying them all at the initial command, separated by spaces or adding a flag for a text/json input would be great. This is definitely lowest priority because anyone can just write their own wrapper script and pass their watch list one at a time to your script.

**Comment by M-rcus** [comment]
Hey,

Sorry for the late response, been a bit busy the past few weeks (and still am unfortunately).

1. Something like this is what I had in mind with issue #9 and I'd most likely go with that kind of a solution (if it works), but I don't know when I would have time to investigate/implement something like that (that goes for anything related to this project).
2. Good idea.
3. I've considered something like this for a while, just wasn't sure how I'd implement it. As you mentioned it's not really a big deal as people can usually create wrapper scripts (ironically I've done exactly that).

**Comment by M-rcus** [comment]
Closing due to the project being archived: https://github.com/M-rcus/yiff-dl#archived
