### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Baramanga** [M-rcus/yiff-dl#15]
I run yiff-dl today and got this error:
TypeError: Cannot read property 'find' of undefined
And yiff-dl can't even fetch pages

**Comment by M-rcus** [comment]
Sorry for the delayed reply.

Are you still having this issue? If so, make sure you're using the latest version (1.2.1) and if you are then I'm gonna need the link to the creator(s) you're having issues with.

At the moment I'm not having issues ripping a handful of creators, so it could've been a temporary issue with the yiff.party web service being down.
